export const propertyFeatures = {
  Accessability: 'נגישה לנכים',
  AC: 'מזגן',
  WindowBars: 'סורגים',
  WaterHeating: 'דוד שמש',
  Elevator: 'מעלית',
  Roommates: 'לשותפים',
  Furniture: 'מרוהטת',
  Unit: 'יחידת דיור',
  KosherKitchen: 'מטבח כשר',
  Pets: 'חיות מחמד',
  Renovated: 'משופצת',
  Mamad: 'ממ״ד',
  TadiranAC: 'מזגן תדיראן',
  Storage: 'מחסן',
};
