export const publish = {
  navbar_publishNewAd: 'פרסום מודעה חדשה',
  navbar_contact: 'צור קשר',

  selectCategory_header: 'אני רוצה לפרסם מודעה בלוח...',
  selectCategory_realestate: 'נדל״ן',
  selectCategory_automobiles: 'כלי רכב',
  selectCategory_secondhand: 'יד שנייה',
  selectCategory_businessForsale: 'עסקים למכירה',
  selectCategory_tradesPerson: 'בעלי מקצוע',
  selectCategory_commercialRealestate: 'נדל״ן מסחרי',
  selectCategory_cellular: 'סלולר',
  selectCategory_furniture: 'ריהוט',
  selectCategory_fashion: 'אופנה וטיפוח',
  selectCategory_pets: 'חיות מחמד',
  selectCategory_children: 'לתינוק ולילד',
  selectCategory_recruiting: 'דרושים',

  selectCategory_realestateDescription: 'מכירה, השכרה, מסחרי',
  selectCategory_automobilesDescription: 'כלי רכב, דו גלגלי, כלי שיט, מיוחדים',
  selectCategory_secondhandDescription:
    'לבית לגינה ולמשרד, חשמל, ספורט, פנאי ושונות',
  selectCategory_businessForsaleDescription: 'הייטק, בתי קפה וכו',
  selectCategory_commercialRealestateDescription: 'הובלות, מוסכים, שיפוצים',
  selectCategory_tradesPersonDescription: 'מחסנים, קליניקות, משרדים',
  selectCategory_cellularDescription: 'מכשירים, אביזרים ושעונים חכמים',

  selectCategory_btn_start: 'מתחילים',
  selectCategory_btn_exit: 'יציאה',

  steps_btn_back: 'חזרה',
  steps_btn_nextStep: 'המשך לשלב הבא',

  step1_titleShowcase: 'באיזה קטגוריה נפרסם היום?',
  step1_titlePreview: 'אני רוצה למכור נכס',
  step1_option_forSsale: 'מכירה',
  step1_option_forRent: 'השכרה',
  step1_option_forRoommates: 'שותפים',
  step1_option_forCommercial: 'מסחרי',

  step2_titleShowcase: 'כתובת הנכס',
  step2_titlePreview: 'כתובת הנכס',
  step2_description: 'סימנו עברוך את שדות החובה, שלא נפספס פרט חשוב',
  step2_ad_title: 'המלצה שלנו',
  step2_ad_description: 'העלאת וידאו של הנכס תמשוך יותר מתעניינים למודעה שלך',
  step2_label_selectPropertyType: 'סוג הנכס',
  step2_placeholder_selectPropertyType: 'דירה או אולי פנטהאוז?',
  step2_label_selectPropertyState: 'מצב הנכס',
  step2_placeholder_selectPropertyState: 'משופץ? חדש מקבלן?',
  step2_option1_selectPropertyState: 'חדש מקבלן (לא גרו בו בכלל)',
  step2_option2_selectPropertyState: 'חדש (נכס בן עד 5 שנים)',
  step2_option3_selectPropertyState: 'משופץ (שופץ ב5 שנים האחרונות',
  step2_option4_selectPropertyState: 'במצב שמור (במצב טוב, לא שופץ)',
  step2_option5_selectPropertyState: 'דרוש שיפוץ (זקוק לעבודת שיפוץ)',
  step2_label_selectCity: 'ישוב',
  step2_placeholder_selectCity: 'איפה נמצא הנכס',
  step2_label_inputAddress: 'רחוב',
  step2_placeholder_inputAddress: 'הכנסת שם הרחוב',
  step2_caption_inputAddress1: 'המידע הזה מגיע מגוף ממשלתי, אם הרחוב שלך לא מופיע',
  step2_caption_inputAddress2: 'מומלץ לבחור רחוב קרוב אליך',
  step2_caption_inputAddress3: 'לא מצאת את הרחוב?',
  step2_label_inputHouseNum: 'מס׳ בית',
  step2_label_selectFloor: 'קומה',
  step2_placeholder_selectFloor: 'מספר קומה',
  step2_label_selectTotalFloors: 'סה״כ קומות בבניין',
  step2_placeholder_selectTotalFloors: 'סה״כ קומות',
  step2_label_inputNeighborhood: 'שכונה',
  step2_label_inputArea: 'אזור',
  step2_caption_governmentInformation: 'המידע הזה מגיע מגוף ממשלתי ולא ניתן לשינוי',
  step2_label_checkboxIsOnColumns: 'על עמודים',
  step2_label_checkboxAllowEmailAds: 'אני רוצה לקבל עדכון חודשי במייל עם הערכת שווי מעודכנת עבור הנכס, עסקאות באיזור והצעות מקצועיות מיועצי נדל״ן',

  step3_titleShowcase: 'על הנכס',
  step3_titlePreview: 'על הנכס',
  step3_label_selectRooms: 'מספר חדרים',
  step3_label_selectParking: 'חניה',
  step3_label_selectBalcony: 'מרפסת',
  step3_label_checkboxFeatures: 'מאפייני הנכס',
  step3_header_description: 'מה חשוב לך שידעו על הנכס?',
  step3_label_description: "פרוט הנכס",
  step3_label_caption1_description: 'הידעת: מודעה ללא תיאור, כמעט ולא מקבלת שיחות',
  step3_label_caption2_description: 'אין צורך להוסיף מספר טלפון כחלק מהתיאור, בהמשך התהליך יש אזור מסודר לזה',
  step3_placeholder_description: 'זה המקום לתאר את הפרטים הבולטים, למשל, האם נערך שיפוץ במבנה, מה שופץ, כיווני אוויר, האווירה ברחוב וכו׳',

  step4_titleShowcase: 'תשלומים, תאריכים ועוד',
  step4_titlePreview: 'תשלומים, תאריכים ועוד',
  step4_label_alert: 'מודעות שעולות םע מחירים לא עגולים מוכרות מהר יותר',
  step4_caption_alert: 'גם לנו היה קשה להאמין',
  step4_label_inputSquareMeter: 'מ״ר בנוי',
  step4_placeholder_inputSquareMeter: 'כמה מ״ר יש בנכס',
  step4_label_inputSquareMeterGarden: 'מ״ר גינה',
  step4_label_inputTotalSquareMeter: 'גודל במ״ר סך הכל',
  step4_label_inputPrice: 'מחיר',
  step4_placholder_inputPrice: 'סכום מינימלי 100',
  step4_label_inputPricePerMeter: 'מחיר למטר',
  step4_label_inputEntryDate: 'תאריך כניסה',
  step4_label_checkboxImmediateEntry: 'מיידי',
  step4_label_checkboxFlexibleEntryDate: 'גמיש',

  step5_titleShowcase: 'תמונות וסרטונים',
  step5_titlePreview: 'תמונות וסרטונים',
  step5_description: `ניתן להעלות עד 10 תמונות ע״י גרירה או לחיצה על כפתור הפלוס. אחרי הבחירה, בחרו את מרכז התמונה כדי שתופיע באתר בצורה המוקטנת הטובה ביותר.
  אין לכם מה לדאוג, בגלריה התמונה תופיע בגודלה המקורי`,
  step5_label_uploadVideo: 'סרטון הנכס',
  step5_label_uploadPicture: 'תמונות הנכס',
  step5_caption_upload: 'גרור ושחרר או העלה את הקובץ שלך',

  step6_titleShowcase: 'פרטי התקשרות',
  step6_titlePreview: 'פרטי התקשרות',
  step6_description: 'באיזה מספר המתעניינים יוכלו להשיג אותך?',
  step6_label_inputName: 'השם שלך',
  step6_label_inputPhoneNumber: 'טלפון',
  step6_label_checkboxVirtualNumber: 'אני רוצה שיופע מספר וירטואלי במודעה שלי',
  step6_caption_checkboxVirtualNumber1:
    'המספר הוירטואלי יינתן בחינם בכפוף למדיניות השירות למעט במקרים המפורטים',
  step6_caption_checkboxVirtualNumber2: 'כאן',
  step6_label_checkboxReceiveCallsOverWeekend:
    'אני רוצה לקבל שיחות מגולשי האתר גם בסופ״ש',
  step6_label_checkboxAcceptsTermsAndPrivacy1: 'רק לקרוא ולאשר את',
  step6_label_checkboxAcceptsTermsAndPrivacy2: 'התקנון',
  step6_label_checkboxRecieveUpdatesOverEmail:
    'אני רוצה שתשלחו לי עדכונים למייל',

  step7_titleShowcase: 'בחירת מסלול',
  step7_description1:
    'זהו, אנחנו בסוף. לנו נשאר לשמור את המודעה שלך, לך נשאר לבחור את מסלול הפרסום.',
  step7_description2: 'באיזה מסלול לפרסם את המודעה? זה הרגע לבלוט מעל כולם',
  step7_label_checkboxAcceptAds:
    'אני מאשר את קבלת דיוור פרסומי הקשור למודעה שפרסמתי באתר יד 2 (להסרה - יש להוריד את הסימון בתיבה)',
  step7_gray_header: 'מודעה אפורה חינם',
  step7_gray_prop1: 'מודעה רגילה ללא הדגשה',
  step7_gray_prop2: 'הקפצה ידנית כל 4 שעות',
  step7_gray_prop3: 'הקפצה אוטומטית פעם ביום',
  step7_gray_priceFree: 'חינם',
  step7_bolded_header: 'מסלול מודגש',
  step7_bolded_prop1: 'מודעה מודגשת בצבע ורוד בהיר.',
  step7_bolded_prop2: 'מפורסמת 28 יום בלוח.',
  step7_bolded_prop3: 'הקפצה אוטומטית פעם 1 ביום.',
  step7_yellow_header: 'מודעה VIP צהובה',
  step7_yellow_prop1: 'מופיעה בצהוב מעל כולם',
  step7_yellow_prop2: 'הקפצה ידנית כל 4 שעות',
  step7_yellow_prop3: 'הקפצה אוטומטית פעם ביום',
  step7_yellow_prop4: 'מקבלת הכי הרבה טלפונים',
  step7_yellow_duration: 'ימים',
  step7_reccommended: 'מומלץ',
  step7_btn_selectTrial: 'בחירה במסלול',
};
