export const searchbox = {
  header_search1: "איזה נכס ל",
  header_search2: " תרצו לחפש?",
  header_properties: "מאפייני דירה",

  all: "הכל",
  select_parking: "חניה",
  select_elevator: "מעלית",
  select_balcony: "מרפסת",
  select_mamad : "ממ״ד",
  select_windowBars : "סורגים",
  select_storage: "מחסן",
  select_accessability: "נגישה לנכים",
  select_renovated: "משופצת",
  select_furnished: "מרוהטת",
  select_exclusivity: "בבלעדיות",
  select_immidiateEntry :"כניסה מיידית",
  select_onlyKibuts: "הצגת מושבים וקיבוצים בלבד",
  select_allPropertyTypes: "כל סוגי הנכסים",
  select_apartments: "דירות",
  select_houses: "בתים",
  select_moreTypes: "סוגים נוספים",

  label_search: "חפשו אזור, עיר, שכונה או רחוב",
  label_floor: "קומה",
  label_freeSearch: "חיפוש חופשי",
  label_propertyType: "סוג נכס",
  label_rooms: "חדרים",
  label_price: "מחיר",
  label_apartmentSize: "גודל דירה (במ״ר)",
  label_entryDate: "תאריך כניסה",

  placeholder_search: "לדוגמא: רחביה, ירושלים",
  placeholder_propertyType: "בחרו סוגי נכסים",
  placeholder_rooms: "חדרים",
  placeholder_from: "מ-",
  placeholder_to: "עד-",
  placeholder_entryDate: "החל מ- הזינו תאריך כניסה",


  btn_advancedSearch: "חיפוש מתקדם",
  btn_search: "חיפוש",
  btn_getAlertsByEmail: "קבלו התראות במייל על החיפוש",
  btn_forsale: "מכירה",
  btn_forrent: "השכרה",
  btn_forroommates: "שותפים",
  btn_forcommercial: "מסחרי",
  btn_clear: "נקה",
  btn_select: 'בחירה'
};
